# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  swapDevices = [];

  # the root + /boot filesystems are owned by disko (modules.disko.proxmox-vm),
  # so they are intentionally not declared here. regenerate with
  # `nixos-generate-config --no-filesystems` to keep it that way.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
